/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.apotekertest.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author himorii
 */
public class LaporanPanel extends JPanel {
    
    private RingkasanPanel ringkasanPanel;
    private PenjualanPanel penjualanPanel;
    private InventarisPanel inventarisPanel;

    private final Color ACTIVE_BG = new Color(20,145,66);
    private final Color ACTIVE_FG = Color.WHITE;

    private final Color NORMAL_BG = Color.WHITE;
    private final Color NORMAL_FG = new Color(20,145,66);
    
    private void showPanel(JPanel panel) {
        tabPanel.removeAll();
        tabPanel.setLayout(new BorderLayout());
        
        tabPanel.add(panel, BorderLayout.CENTER);
        
        tabPanel.revalidate();
        tabPanel.repaint();
    }
    
    private void setActiveMenu(JButton activeButton) {

        JButton[] buttons = {
            btnRingkasanPanel,
            btnPenjualanPanel,
            btnInventarisPanel
        };

        for (JButton btn : buttons) {

            btn.setBackground(NORMAL_BG);
            btn.setForeground(NORMAL_FG);

            btn.setOpaque(true);
            btn.setBorderPainted(false);
        }

        activeButton.setBackground(ACTIVE_BG);
        activeButton.setForeground(ACTIVE_FG);
}

    /**
     * Creates new form DashboardContentPanel
     */
    public LaporanPanel() {
        initComponents();
        headerContainer.setLayout(new BorderLayout());
        headerContainer.add(new HeaderPanel(MainApp.stokService), BorderLayout.CENTER);

        ringkasanPanel = new RingkasanPanel();
        penjualanPanel = new PenjualanPanel();
        inventarisPanel = new InventarisPanel();

        showPanel(ringkasanPanel);
        setActiveMenu(btnRingkasanPanel);
        contentScrollPane.getVerticalScrollBar().setUnitIncrement(16);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentScrollPane = new javax.swing.JScrollPane();
        contentContainer = new javax.swing.JPanel();
        btnRingkasanPanel = new javax.swing.JButton();
        headerContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalObatOTCPanel4 = new javax.swing.JPanel();
        labelTotalProduk4 = new javax.swing.JLabel();
        totalTransaksi = new javax.swing.JLabel();
        labelKenaikanDanKeturunanTotalTransaksi = new javax.swing.JLabel();
        totalObatOTCPanel3 = new javax.swing.JPanel();
        labelTotalProduk3 = new javax.swing.JLabel();
        totalNonObat = new javax.swing.JLabel();
        labelKenaikanDanKeturunanTotalNonObat = new javax.swing.JLabel();
        totalObatOTCPanel2 = new javax.swing.JPanel();
        labelTotalProduk2 = new javax.swing.JLabel();
        totalBahanRacikan = new javax.swing.JLabel();
        labelKenaikanDanKeturunanTotalBahanRacikan = new javax.swing.JLabel();
        totalObatOTCPanel1 = new javax.swing.JPanel();
        labelTotalProduk1 = new javax.swing.JLabel();
        totalObatOTC = new javax.swing.JLabel();
        labelKenaikanDanKeturunanTotalObatOTC = new javax.swing.JLabel();
        totalObatOTCPanel = new javax.swing.JPanel();
        labelTotalProduk = new javax.swing.JLabel();
        totalProduk = new javax.swing.JLabel();
        labelKenaikanDanKeturunanTotalProduk = new javax.swing.JLabel();
        btnPenjualanPanel = new javax.swing.JButton();
        btnInventarisPanel = new javax.swing.JButton();
        tabPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(240, 252, 245));

        contentContainer.setBackground(new java.awt.Color(240, 252, 245));

        btnRingkasanPanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRingkasanPanel.setForeground(new java.awt.Color(0, 155, 54));
        btnRingkasanPanel.setText("Ringkasan");
        btnRingkasanPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRingkasanPanel.setPreferredSize(new java.awt.Dimension(210, 50));
        btnRingkasanPanel.addActionListener(this::btnRingkasanPanelActionPerformed);

        headerContainer.setMinimumSize(new java.awt.Dimension(100, 80));
        headerContainer.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout headerContainerLayout = new javax.swing.GroupLayout(headerContainer);
        headerContainer.setLayout(headerContainerLayout);
        headerContainerLayout.setHorizontalGroup(
            headerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headerContainerLayout.setVerticalGroup(
            headerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 137, 79));
        jLabel1.setText("Analisis inventaris, penjualan, stok, dan expired produk apotek");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 145, 66));
        jLabel2.setText("Laporan Apotek");

        totalObatOTCPanel4.setBackground(new java.awt.Color(255, 255, 255));
        totalObatOTCPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalObatOTCPanel4.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalProduk4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalProduk4.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalProduk4.setText("Total Transaksi");

        totalTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalTransaksi.setForeground(new java.awt.Color(42, 137, 79));
        totalTransaksi.setText("0");

        labelKenaikanDanKeturunanTotalTransaksi.setForeground(new java.awt.Color(42, 137, 79));
        labelKenaikanDanKeturunanTotalTransaksi.setText("+0%");

        javax.swing.GroupLayout totalObatOTCPanel4Layout = new javax.swing.GroupLayout(totalObatOTCPanel4);
        totalObatOTCPanel4.setLayout(totalObatOTCPanel4Layout);
        totalObatOTCPanel4Layout.setHorizontalGroup(
            totalObatOTCPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalObatOTCPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalObatOTCPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalProduk4, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(totalTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelKenaikanDanKeturunanTotalTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalObatOTCPanel4Layout.setVerticalGroup(
            totalObatOTCPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalObatOTCPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalProduk4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelKenaikanDanKeturunanTotalTransaksi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalObatOTCPanel3.setBackground(new java.awt.Color(255, 255, 255));
        totalObatOTCPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalObatOTCPanel3.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalProduk3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalProduk3.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalProduk3.setText("Total NonObat");

        totalNonObat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalNonObat.setForeground(new java.awt.Color(42, 137, 79));
        totalNonObat.setText("0");

        labelKenaikanDanKeturunanTotalNonObat.setForeground(new java.awt.Color(255, 0, 58));
        labelKenaikanDanKeturunanTotalNonObat.setText("-0%");

        javax.swing.GroupLayout totalObatOTCPanel3Layout = new javax.swing.GroupLayout(totalObatOTCPanel3);
        totalObatOTCPanel3.setLayout(totalObatOTCPanel3Layout);
        totalObatOTCPanel3Layout.setHorizontalGroup(
            totalObatOTCPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalObatOTCPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalObatOTCPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalProduk3, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(totalNonObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelKenaikanDanKeturunanTotalNonObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalObatOTCPanel3Layout.setVerticalGroup(
            totalObatOTCPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalObatOTCPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalProduk3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalNonObat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelKenaikanDanKeturunanTotalNonObat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalObatOTCPanel2.setBackground(new java.awt.Color(255, 255, 255));
        totalObatOTCPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalObatOTCPanel2.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalProduk2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalProduk2.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalProduk2.setText("Total Bahan Racikan");

        totalBahanRacikan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalBahanRacikan.setForeground(new java.awt.Color(42, 137, 79));
        totalBahanRacikan.setText("0");

        labelKenaikanDanKeturunanTotalBahanRacikan.setForeground(new java.awt.Color(42, 137, 79));
        labelKenaikanDanKeturunanTotalBahanRacikan.setText("+0%");

        javax.swing.GroupLayout totalObatOTCPanel2Layout = new javax.swing.GroupLayout(totalObatOTCPanel2);
        totalObatOTCPanel2.setLayout(totalObatOTCPanel2Layout);
        totalObatOTCPanel2Layout.setHorizontalGroup(
            totalObatOTCPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalObatOTCPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalObatOTCPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalProduk2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalBahanRacikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelKenaikanDanKeturunanTotalBahanRacikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalObatOTCPanel2Layout.setVerticalGroup(
            totalObatOTCPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalObatOTCPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalProduk2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalBahanRacikan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelKenaikanDanKeturunanTotalBahanRacikan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalObatOTCPanel1.setBackground(new java.awt.Color(255, 255, 255));
        totalObatOTCPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalObatOTCPanel1.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalProduk1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalProduk1.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalProduk1.setText("Total Obat OTC");

        totalObatOTC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalObatOTC.setForeground(new java.awt.Color(42, 137, 79));
        totalObatOTC.setText("0");

        labelKenaikanDanKeturunanTotalObatOTC.setForeground(new java.awt.Color(42, 137, 79));
        labelKenaikanDanKeturunanTotalObatOTC.setText("+0%");

        javax.swing.GroupLayout totalObatOTCPanel1Layout = new javax.swing.GroupLayout(totalObatOTCPanel1);
        totalObatOTCPanel1.setLayout(totalObatOTCPanel1Layout);
        totalObatOTCPanel1Layout.setHorizontalGroup(
            totalObatOTCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalObatOTCPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalObatOTCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalProduk1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(totalObatOTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelKenaikanDanKeturunanTotalObatOTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalObatOTCPanel1Layout.setVerticalGroup(
            totalObatOTCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalObatOTCPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalProduk1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalObatOTC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelKenaikanDanKeturunanTotalObatOTC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalObatOTCPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalObatOTCPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalObatOTCPanel.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalProduk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalProduk.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalProduk.setText("Total Produk");

        totalProduk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalProduk.setForeground(new java.awt.Color(42, 137, 79));
        totalProduk.setText("0");

        labelKenaikanDanKeturunanTotalProduk.setForeground(new java.awt.Color(42, 137, 79));
        labelKenaikanDanKeturunanTotalProduk.setText("+0%");

        javax.swing.GroupLayout totalObatOTCPanelLayout = new javax.swing.GroupLayout(totalObatOTCPanel);
        totalObatOTCPanel.setLayout(totalObatOTCPanelLayout);
        totalObatOTCPanelLayout.setHorizontalGroup(
            totalObatOTCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalObatOTCPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalObatOTCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalProduk, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(totalProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelKenaikanDanKeturunanTotalProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalObatOTCPanelLayout.setVerticalGroup(
            totalObatOTCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalObatOTCPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelKenaikanDanKeturunanTotalProduk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPenjualanPanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPenjualanPanel.setForeground(new java.awt.Color(0, 155, 54));
        btnPenjualanPanel.setText("Penjualan");
        btnPenjualanPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPenjualanPanel.setPreferredSize(new java.awt.Dimension(210, 50));
        btnPenjualanPanel.addActionListener(this::btnPenjualanPanelActionPerformed);

        btnInventarisPanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInventarisPanel.setForeground(new java.awt.Color(0, 155, 54));
        btnInventarisPanel.setText("Inventaris");
        btnInventarisPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInventarisPanel.setPreferredSize(new java.awt.Dimension(210, 50));
        btnInventarisPanel.addActionListener(this::btnInventarisPanelActionPerformed);

        tabPanel.setMaximumSize(new java.awt.Dimension(1019, 810));
        tabPanel.setPreferredSize(new java.awt.Dimension(1019, 810));

        javax.swing.GroupLayout tabPanelLayout = new javax.swing.GroupLayout(tabPanel);
        tabPanel.setLayout(tabPanelLayout);
        tabPanelLayout.setHorizontalGroup(
            tabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        tabPanelLayout.setVerticalGroup(
            tabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contentContainerLayout = new javax.swing.GroupLayout(contentContainer);
        contentContainer.setLayout(contentContainerLayout);
        contentContainerLayout.setHorizontalGroup(
            contentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
            .addGroup(contentContainerLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(contentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentContainerLayout.createSequentialGroup()
                        .addGroup(contentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentContainerLayout.createSequentialGroup()
                                .addComponent(btnRingkasanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPenjualanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnInventarisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(contentContainerLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(totalObatOTCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totalObatOTCPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totalObatOTCPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totalObatOTCPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totalObatOTCPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contentContainerLayout.setVerticalGroup(
            contentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentContainerLayout.createSequentialGroup()
                .addComponent(headerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalObatOTCPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalObatOTCPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalObatOTCPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalObatOTCPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalObatOTCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRingkasanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPenjualanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventarisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        contentScrollPane.setViewportView(contentContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRingkasanPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRingkasanPanelActionPerformed
        setActiveMenu(btnRingkasanPanel);
        showPanel(ringkasanPanel);
    }//GEN-LAST:event_btnRingkasanPanelActionPerformed

    private void btnPenjualanPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanPanelActionPerformed
        setActiveMenu(btnPenjualanPanel);
        showPanel(penjualanPanel);
    }//GEN-LAST:event_btnPenjualanPanelActionPerformed

    private void btnInventarisPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarisPanelActionPerformed
        setActiveMenu(btnInventarisPanel);
        showPanel(inventarisPanel);
    }//GEN-LAST:event_btnInventarisPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventarisPanel;
    private javax.swing.JButton btnPenjualanPanel;
    private javax.swing.JButton btnRingkasanPanel;
    private javax.swing.JPanel contentContainer;
    private javax.swing.JScrollPane contentScrollPane;
    private javax.swing.JPanel headerContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelKenaikanDanKeturunanTotalBahanRacikan;
    private javax.swing.JLabel labelKenaikanDanKeturunanTotalNonObat;
    private javax.swing.JLabel labelKenaikanDanKeturunanTotalObatOTC;
    private javax.swing.JLabel labelKenaikanDanKeturunanTotalProduk;
    private javax.swing.JLabel labelKenaikanDanKeturunanTotalTransaksi;
    private javax.swing.JLabel labelTotalProduk;
    private javax.swing.JLabel labelTotalProduk1;
    private javax.swing.JLabel labelTotalProduk2;
    private javax.swing.JLabel labelTotalProduk3;
    private javax.swing.JLabel labelTotalProduk4;
    private javax.swing.JPanel tabPanel;
    private javax.swing.JLabel totalBahanRacikan;
    private javax.swing.JLabel totalNonObat;
    private javax.swing.JLabel totalObatOTC;
    private javax.swing.JPanel totalObatOTCPanel;
    private javax.swing.JPanel totalObatOTCPanel1;
    private javax.swing.JPanel totalObatOTCPanel2;
    private javax.swing.JPanel totalObatOTCPanel3;
    private javax.swing.JPanel totalObatOTCPanel4;
    private javax.swing.JLabel totalProduk;
    private javax.swing.JLabel totalTransaksi;
    // End of variables declaration//GEN-END:variables
}
