/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apotekertest.ui;

import com.mycompany.apotekertest.model.Apoteker;
import com.mycompany.apotekertest.model.PJApoteker;
import com.mycompany.apotekertest.repository.UserRepository;
import com.mycompany.apotekertest.service.StokService;
import com.mycompany.apotekertest.stok.StokBahanRacikan;
import com.mycompany.apotekertest.stok.StokNonObat;
import com.mycompany.apotekertest.stok.StokObatOTC;
import com.mycompany.apotekertest.service.TransaksiService;
import javax.swing.SwingUtilities;

/**
 *
 * @author Kelompok Kipli
 */
public class MainApp extends javax.swing.JFrame {

    public static UserRepository userRepository = new UserRepository();

    // Stok global
    public static StokObatOTC stokObatOTC = new StokObatOTC(5);
    public static StokBahanRacikan stokBahanRacikan = new StokBahanRacikan(10);
    public static StokNonObat stokNonObat = new StokNonObat(5);
    public static StokService stokService = new StokService(stokObatOTC, stokBahanRacikan, stokNonObat);
    public static TransaksiService transaksiService = new TransaksiService();

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            stokService.tambahObat(
                    "Analgesik",
                    500,
                    1000,
                    "OBT001",
                    "Paracetamol",
                    6,
                    5,
                    "2027-12-31",
                    "Obat demam"
            );

            stokService.tambahObat(
                    "Vitamin",
                    1000,
                    2000,
                    "OBT002",
                    "Vitamin C",
                    2,
                    5,
                    "2026-06-23",
                    "Vitamin"
            );

            // Contoh data dengan satuan yang bervariasi
            stokService.tambahBahanRacikan(
                    "BR001", 
                    "Asam Salisilat", 
                    "g", 
                    500, 
                    50, 
                    "2027-10-15", 
                    "Bahan dasar salep racikan"
            );
            
            stokService.tambahBahanRacikan(
                    "BR002", 
                    "Glukosa Anhidrat", 
                    "kg", 
                    5, 
                    1, 
                    "2028-01-20", 
                    "Bahan tambahan serbuk"
            );
            
            stokService.tambahBahanRacikan(
                    "BR003", 
                    "Aqua Destillata", 
                    "ml", 
                    2000,
                    500, 
                    "2026-06-27", 
                    "Pelarut untuk sirup"
            );
            
            stokService.tambahBahanRacikan(
                    "BR004", 
                    "Paracetamol Serbuk",
                    "mg", 
                    10000,
                    1000,
                    "2027-05-12", 
                    "Bahan aktif puyer anak"
            );

            stokService.tambahNonObat(
                    "Perawatan",
                    45000.0, 
                    65000.0, 
                    "NO006", 
                    "Sabun Antiseptik", 
                    60, 
                    10, 
                    "2027-04-12", 
                    "Sabun cair antiseptik 250ml"
            );
            
            stokService.tambahNonObat(
                    "Alat kesehatan", 
                    12000.0, 
                    20000.0, 
                    "NO007", 
                    "Perban Elastis", 
                    80, 
                    15,
                    "2029-05-20",
                    "Perban untuk cedera otot"
            );
            
            stokService.tambahNonObat("Bayi", 
                    95000.0,
                    130000.0, 
                    "NO008", 
                    "Minyak Telon",
                    25, 
                    5, 
                    "2028-09-15", 
                    "Minyak penghangat bayi 100ml"
            );
            
            stokService.tambahNonObat(
                    "Perawatan", 
                    28000.0,
                    40000.0, 
                    "NO009",
                    "Plester Luka",
                    150,
                    30,
                    "2030-01-10", 
                    "Plester kain steril isi 20"
            );
            
        } catch (Exception e) {
            e.printStackTrace();
        }

        SwingUtilities.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
