/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apotekertest.ui;

import com.mycompany.apotekertest.model.Apoteker;
import com.mycompany.apotekertest.model.PJApoteker;
import com.mycompany.apotekertest.repository.UserRepository;
import com.mycompany.apotekertest.stok.StokBahanRacikan;
import com.mycompany.apotekertest.stok.StokNonObat;
import com.mycompany.apotekertest.stok.StokObatOTC;
import javax.swing.SwingUtilities;

/**
 *
 * @author Kelompok Kipli
 */
public class MainApp extends javax.swing.JFrame {
    
    public static UserRepository userRepository = new UserRepository();

    // Stok global
    public static StokObatOTC stokObatOTC = new StokObatOTC(5);
    public static StokBahanRacikan stokBahanRacikan = new StokBahanRacikan(10);
    public static StokNonObat stokNonObat = new StokNonObat(5);

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Daftarkan user ke repository
        userRepository.tambahUser(new Apoteker("APT001", "Budi Santoso", "budi123", "Pagi"));
        userRepository.tambahUser(new Apoteker("APT002", "Sari Dewi",   "sari123", "Sore"));
        userRepository.tambahUser(new PJApoteker("PJA001", "Dr. Ahmad", "pja123"));

        SwingUtilities.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
