/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.apotekertest.ui;

import java.awt.BorderLayout;

/**
 *
 * @author himorii
 */
public class NotifikasiPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProdukPanel
     */
    public NotifikasiPanel() {
        initComponents();
        headerContainer.setLayout(new BorderLayout());
        headerContainer.add(new HeaderPanel(MainApp.stokService), BorderLayout.CENTER);
        contentScrollPane.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        contentScrollPane = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        headerContainer = new javax.swing.JPanel();
        lblTitleObatOTC = new javax.swing.JLabel();
        lblDescriptionObatOTC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNotifikasi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnNext1 = new javax.swing.JButton();
        totalNotifikasiKritisPanel3 = new javax.swing.JPanel();
        labelTotalNotifikasiBerhasil = new javax.swing.JLabel();
        totalNotifikasiBerhasil = new javax.swing.JLabel();
        totalNotifikasiKritisPanel2 = new javax.swing.JPanel();
        labelTotalNotifikasiInfo = new javax.swing.JLabel();
        totalNotifikasiInfo = new javax.swing.JLabel();
        totalNotifikasiKritisPanel1 = new javax.swing.JPanel();
        labelTotalNotifikasiPeringatan = new javax.swing.JLabel();
        totalNotifikasiPeringatan = new javax.swing.JLabel();
        totalNotifikasiKritisPanel = new javax.swing.JPanel();
        labelTotalNotifikasiKritis = new javax.swing.JLabel();
        totalNotifikasiKritis = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setMaximumSize(new java.awt.Dimension(32767, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        contentScrollPane.setMaximumSize(new java.awt.Dimension(32767, 800));
        contentScrollPane.setPreferredSize(new java.awt.Dimension(1082, 800));

        contentPanel.setBackground(new java.awt.Color(240, 252, 245));
        contentPanel.setMaximumSize(new java.awt.Dimension(32767, 800));
        contentPanel.setPreferredSize(new java.awt.Dimension(1080, 800));

        headerContainer.setMinimumSize(new java.awt.Dimension(100, 80));
        headerContainer.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout headerContainerLayout = new javax.swing.GroupLayout(headerContainer);
        headerContainer.setLayout(headerContainerLayout);
        headerContainerLayout.setHorizontalGroup(
            headerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headerContainerLayout.setVerticalGroup(
            headerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        lblTitleObatOTC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitleObatOTC.setForeground(new java.awt.Color(20, 145, 66));
        lblTitleObatOTC.setText("Notifikasi");

        lblDescriptionObatOTC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescriptionObatOTC.setForeground(new java.awt.Color(42, 137, 79));
        lblDescriptionObatOTC.setText("Semua pemberitahuan sistem inventaris");

        tableNotifikasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableNotifikasi);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 137, 79));
        jLabel1.setText("Menampilkan 0 dari 0 transaksi");

        btnPrevious.setBackground(new java.awt.Color(20, 145, 66));
        btnPrevious.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious.setText("Sebelumnya");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 137, 79));
        jLabel2.setText("Halaman 0 dari 0");

        btnNext1.setBackground(new java.awt.Color(20, 145, 66));
        btnNext1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNext1.setForeground(new java.awt.Color(255, 255, 255));
        btnNext1.setText("Selanjutnya");

        totalNotifikasiKritisPanel3.setBackground(new java.awt.Color(255, 255, 255));
        totalNotifikasiKritisPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalNotifikasiKritisPanel3.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalNotifikasiBerhasil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalNotifikasiBerhasil.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalNotifikasiBerhasil.setText("Berhasil");

        totalNotifikasiBerhasil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalNotifikasiBerhasil.setForeground(new java.awt.Color(42, 137, 79));
        totalNotifikasiBerhasil.setText("0");

        javax.swing.GroupLayout totalNotifikasiKritisPanel3Layout = new javax.swing.GroupLayout(totalNotifikasiKritisPanel3);
        totalNotifikasiKritisPanel3.setLayout(totalNotifikasiKritisPanel3Layout);
        totalNotifikasiKritisPanel3Layout.setHorizontalGroup(
            totalNotifikasiKritisPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalNotifikasiKritisPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalNotifikasiBerhasil, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiBerhasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalNotifikasiKritisPanel3Layout.setVerticalGroup(
            totalNotifikasiKritisPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalNotifikasiBerhasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalNotifikasiBerhasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        totalNotifikasiKritisPanel2.setBackground(new java.awt.Color(255, 255, 255));
        totalNotifikasiKritisPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalNotifikasiKritisPanel2.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalNotifikasiInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalNotifikasiInfo.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalNotifikasiInfo.setText("Info");

        totalNotifikasiInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalNotifikasiInfo.setForeground(new java.awt.Color(42, 137, 79));
        totalNotifikasiInfo.setText("0");

        javax.swing.GroupLayout totalNotifikasiKritisPanel2Layout = new javax.swing.GroupLayout(totalNotifikasiKritisPanel2);
        totalNotifikasiKritisPanel2.setLayout(totalNotifikasiKritisPanel2Layout);
        totalNotifikasiKritisPanel2Layout.setHorizontalGroup(
            totalNotifikasiKritisPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalNotifikasiKritisPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalNotifikasiInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalNotifikasiKritisPanel2Layout.setVerticalGroup(
            totalNotifikasiKritisPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalNotifikasiInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalNotifikasiInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        totalNotifikasiKritisPanel1.setBackground(new java.awt.Color(255, 255, 255));
        totalNotifikasiKritisPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalNotifikasiKritisPanel1.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalNotifikasiPeringatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalNotifikasiPeringatan.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalNotifikasiPeringatan.setText("Transaksi Hari ini");

        totalNotifikasiPeringatan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalNotifikasiPeringatan.setForeground(new java.awt.Color(241, 140, 163));
        totalNotifikasiPeringatan.setText("0");

        javax.swing.GroupLayout totalNotifikasiKritisPanel1Layout = new javax.swing.GroupLayout(totalNotifikasiKritisPanel1);
        totalNotifikasiKritisPanel1.setLayout(totalNotifikasiKritisPanel1Layout);
        totalNotifikasiKritisPanel1Layout.setHorizontalGroup(
            totalNotifikasiKritisPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalNotifikasiKritisPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalNotifikasiPeringatan, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiPeringatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalNotifikasiKritisPanel1Layout.setVerticalGroup(
            totalNotifikasiKritisPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalNotifikasiPeringatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalNotifikasiPeringatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        totalNotifikasiKritisPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalNotifikasiKritisPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalNotifikasiKritisPanel.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalNotifikasiKritis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalNotifikasiKritis.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalNotifikasiKritis.setText("Kritis");

        totalNotifikasiKritis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalNotifikasiKritis.setForeground(new java.awt.Color(241, 140, 163));
        totalNotifikasiKritis.setText("0");

        javax.swing.GroupLayout totalNotifikasiKritisPanelLayout = new javax.swing.GroupLayout(totalNotifikasiKritisPanel);
        totalNotifikasiKritisPanel.setLayout(totalNotifikasiKritisPanelLayout);
        totalNotifikasiKritisPanelLayout.setHorizontalGroup(
            totalNotifikasiKritisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalNotifikasiKritisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalNotifikasiKritis, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiKritis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalNotifikasiKritisPanelLayout.setVerticalGroup(
            totalNotifikasiKritisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalNotifikasiKritis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalNotifikasiKritis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrevious)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDescriptionObatOTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitleObatOTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(totalNotifikasiKritisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalNotifikasiKritisPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalNotifikasiKritisPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalNotifikasiKritisPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addComponent(headerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblTitleObatOTC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescriptionObatOTC)
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalNotifikasiKritisPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiKritisPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiKritisPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiKritisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(btnNext1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                .addGap(859, 859, 859))
        );

        contentScrollPane.setViewportView(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JScrollPane contentScrollPane;
    private javax.swing.JPanel headerContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotalNotifikasiBerhasil;
    private javax.swing.JLabel labelTotalNotifikasiInfo;
    private javax.swing.JLabel labelTotalNotifikasiKritis;
    private javax.swing.JLabel labelTotalNotifikasiPeringatan;
    private javax.swing.JLabel lblDescriptionObatOTC;
    private javax.swing.JLabel lblTitleObatOTC;
    private javax.swing.JTable tableNotifikasi;
    private javax.swing.JLabel totalNotifikasiBerhasil;
    private javax.swing.JLabel totalNotifikasiInfo;
    private javax.swing.JLabel totalNotifikasiKritis;
    private javax.swing.JPanel totalNotifikasiKritisPanel;
    private javax.swing.JPanel totalNotifikasiKritisPanel1;
    private javax.swing.JPanel totalNotifikasiKritisPanel2;
    private javax.swing.JPanel totalNotifikasiKritisPanel3;
    private javax.swing.JLabel totalNotifikasiPeringatan;
    // End of variables declaration//GEN-END:variables
}
