/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.apotekertest.ui;

import com.mycompany.apotekertest.model.Notifikasi;
import com.mycompany.apotekertest.observer.NotifikasiObserver;
import java.awt.BorderLayout;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author himorii
 */
public class NotifikasiPanel extends javax.swing.JPanel implements NotifikasiObserver {
    private List<Notifikasi> notifikasiStok;
    private Timer refreshTimer;
    
    private void loadStatistik() {
        int kritis = 0;
        int info = 0;
        int warning = 0;
        int sukses = 0;
    
        for(Notifikasi notif : MainApp.notifikasiManager.getAllNotifikasi()) {
            switch(notif.getTipe()) {
                case "CRITICAL":
                    kritis++;
                    break;
                    
                case "WARNING":
                    warning++;
                    break;
                    
                case "INFO":
                    info++;
                    break;
                  
                case "SUCCESS":
                    sukses++;
                    break;
            }
        }
        
        totalNotifikasiKritis.setText(String.valueOf(kritis));
        totalNotifikasiInfo.setText(String.valueOf(info));
        totalNotifikasiPeringatan.setText(String.valueOf(warning));
        totalNotifikasiBerhasil.setText(String.valueOf(sukses));
    }
    
    private void loadTabelNotifikasi() {      
        notifikasiStok = MainApp.notifikasiManager.getAllNotifikasi();
        
        DefaultTableModel model = (DefaultTableModel) tableNotifikasi.getModel();
        
        model.setRowCount(0);
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        
        for(Notifikasi notif : notifikasiStok) {            
            model.addRow(new Object[] {
                notif.getTanggal().format(formatter),
                notif.getJudul(),
                notif.getTipe(),
                notif.getPesan(),
                notif.getPrioritas(),
                notif.isStatusBaca() ? "Dibaca" : "Belum Dibaca",
            });
        }
    }
    
    @Override
    public void updateNotifikasi() {
        loadStatistik();
        loadTabelNotifikasi();
    }

    /**
     * Creates new form ProdukPanel
     */
    public NotifikasiPanel() {
        initComponents();
        
        MainApp.notifikasiManager.addObserver(this);
        
        updateNotifikasi();
        
        headerContainer.setLayout(new BorderLayout());
        headerContainer.add(new HeaderPanel(MainApp.stokService), BorderLayout.CENTER);
        contentScrollPane.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        contentScrollPane = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        headerContainer = new javax.swing.JPanel();
        lblTitleObatOTC = new javax.swing.JLabel();
        lblDescriptionObatOTC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNotifikasi = new javax.swing.JTable();
        totalNotifikasiKritisPanel3 = new javax.swing.JPanel();
        labelTotalNotifikasiBerhasil = new javax.swing.JLabel();
        totalNotifikasiBerhasil = new javax.swing.JLabel();
        totalNotifikasiKritisPanel2 = new javax.swing.JPanel();
        labelTotalNotifikasiInfo = new javax.swing.JLabel();
        totalNotifikasiInfo = new javax.swing.JLabel();
        totalNotifikasiKritisPanel1 = new javax.swing.JPanel();
        labelTotalNotifikasiPeringatan = new javax.swing.JLabel();
        totalNotifikasiPeringatan = new javax.swing.JLabel();
        totalNotifikasiKritisPanel = new javax.swing.JPanel();
        labelTotalNotifikasiKritis = new javax.swing.JLabel();
        totalNotifikasiKritis = new javax.swing.JLabel();
        btnHapusNotifikasi = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setMaximumSize(new java.awt.Dimension(32767, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        contentScrollPane.setMaximumSize(new java.awt.Dimension(32767, 800));
        contentScrollPane.setPreferredSize(new java.awt.Dimension(1082, 800));

        contentPanel.setBackground(new java.awt.Color(240, 252, 245));
        contentPanel.setMaximumSize(new java.awt.Dimension(32767, 800));
        contentPanel.setPreferredSize(new java.awt.Dimension(1080, 800));

        headerContainer.setMinimumSize(new java.awt.Dimension(100, 80));
        headerContainer.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout headerContainerLayout = new javax.swing.GroupLayout(headerContainer);
        headerContainer.setLayout(headerContainerLayout);
        headerContainerLayout.setHorizontalGroup(
            headerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headerContainerLayout.setVerticalGroup(
            headerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        lblTitleObatOTC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitleObatOTC.setForeground(new java.awt.Color(20, 145, 66));
        lblTitleObatOTC.setText("Notifikasi");

        lblDescriptionObatOTC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescriptionObatOTC.setForeground(new java.awt.Color(42, 137, 79));
        lblDescriptionObatOTC.setText("Semua pemberitahuan sistem inventaris");

        tableNotifikasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Judul", "Tipe", "Pesan", "Prioritas", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableNotifikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNotifikasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNotifikasi);

        totalNotifikasiKritisPanel3.setBackground(new java.awt.Color(255, 255, 255));
        totalNotifikasiKritisPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalNotifikasiKritisPanel3.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalNotifikasiBerhasil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalNotifikasiBerhasil.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalNotifikasiBerhasil.setText("Berhasil");

        totalNotifikasiBerhasil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalNotifikasiBerhasil.setForeground(new java.awt.Color(42, 137, 79));
        totalNotifikasiBerhasil.setText("0");

        javax.swing.GroupLayout totalNotifikasiKritisPanel3Layout = new javax.swing.GroupLayout(totalNotifikasiKritisPanel3);
        totalNotifikasiKritisPanel3.setLayout(totalNotifikasiKritisPanel3Layout);
        totalNotifikasiKritisPanel3Layout.setHorizontalGroup(
            totalNotifikasiKritisPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalNotifikasiKritisPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalNotifikasiBerhasil, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiBerhasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalNotifikasiKritisPanel3Layout.setVerticalGroup(
            totalNotifikasiKritisPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalNotifikasiBerhasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalNotifikasiBerhasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        totalNotifikasiKritisPanel2.setBackground(new java.awt.Color(255, 255, 255));
        totalNotifikasiKritisPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalNotifikasiKritisPanel2.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalNotifikasiInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalNotifikasiInfo.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalNotifikasiInfo.setText("Info");

        totalNotifikasiInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalNotifikasiInfo.setForeground(new java.awt.Color(42, 137, 79));
        totalNotifikasiInfo.setText("0");

        javax.swing.GroupLayout totalNotifikasiKritisPanel2Layout = new javax.swing.GroupLayout(totalNotifikasiKritisPanel2);
        totalNotifikasiKritisPanel2.setLayout(totalNotifikasiKritisPanel2Layout);
        totalNotifikasiKritisPanel2Layout.setHorizontalGroup(
            totalNotifikasiKritisPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalNotifikasiKritisPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalNotifikasiInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalNotifikasiKritisPanel2Layout.setVerticalGroup(
            totalNotifikasiKritisPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalNotifikasiInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalNotifikasiInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        totalNotifikasiKritisPanel1.setBackground(new java.awt.Color(255, 255, 255));
        totalNotifikasiKritisPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalNotifikasiKritisPanel1.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalNotifikasiPeringatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalNotifikasiPeringatan.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalNotifikasiPeringatan.setText("Peringatan");

        totalNotifikasiPeringatan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalNotifikasiPeringatan.setForeground(new java.awt.Color(255, 153, 0));
        totalNotifikasiPeringatan.setText("0");

        javax.swing.GroupLayout totalNotifikasiKritisPanel1Layout = new javax.swing.GroupLayout(totalNotifikasiKritisPanel1);
        totalNotifikasiKritisPanel1.setLayout(totalNotifikasiKritisPanel1Layout);
        totalNotifikasiKritisPanel1Layout.setHorizontalGroup(
            totalNotifikasiKritisPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalNotifikasiKritisPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalNotifikasiPeringatan, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiPeringatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalNotifikasiKritisPanel1Layout.setVerticalGroup(
            totalNotifikasiKritisPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalNotifikasiPeringatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalNotifikasiPeringatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        totalNotifikasiKritisPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalNotifikasiKritisPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalNotifikasiKritisPanel.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalNotifikasiKritis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalNotifikasiKritis.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalNotifikasiKritis.setText("Kritis");

        totalNotifikasiKritis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalNotifikasiKritis.setForeground(new java.awt.Color(255, 0, 0));
        totalNotifikasiKritis.setText("0");

        javax.swing.GroupLayout totalNotifikasiKritisPanelLayout = new javax.swing.GroupLayout(totalNotifikasiKritisPanel);
        totalNotifikasiKritisPanel.setLayout(totalNotifikasiKritisPanelLayout);
        totalNotifikasiKritisPanelLayout.setHorizontalGroup(
            totalNotifikasiKritisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalNotifikasiKritisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalNotifikasiKritis, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiKritis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalNotifikasiKritisPanelLayout.setVerticalGroup(
            totalNotifikasiKritisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNotifikasiKritisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalNotifikasiKritis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalNotifikasiKritis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnHapusNotifikasi.setBackground(new java.awt.Color(20, 145, 66));
        btnHapusNotifikasi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHapusNotifikasi.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusNotifikasi.setText("HAPUS NOTIFIKASI");
        btnHapusNotifikasi.setBorder(null);
        btnHapusNotifikasi.addActionListener(this::btnHapusNotifikasiActionPerformed);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(totalNotifikasiKritisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalNotifikasiKritisPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalNotifikasiKritisPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalNotifikasiKritisPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDescriptionObatOTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTitleObatOTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapusNotifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(headerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblTitleObatOTC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescriptionObatOTC))
                    .addComponent(btnHapusNotifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalNotifikasiKritisPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiKritisPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiKritisPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalNotifikasiKritisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contentScrollPane.setViewportView(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableNotifikasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNotifikasiMouseClicked
        int row = tableNotifikasi.getSelectedRow();
        
        if(row >= 0) {
            Notifikasi notif = notifikasiStok.get(row);
            
            if(!notif.isStatusBaca()) {                
                MainApp.notifikasiManager.tandaiDibaca(notif.getIdNotifikasi());
            }
        }
    }//GEN-LAST:event_tableNotifikasiMouseClicked

    private void btnHapusNotifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusNotifikasiActionPerformed
        int row = tableNotifikasi.getSelectedRow();
        
        if(row < 0) {
            JOptionPane.showMessageDialog(this, "Pilih notifikasi yang ingin dihapus!", "Peringatan", WARNING_MESSAGE);
            return;
        }
        
        Notifikasi notif = notifikasiStok.get(row);
        
        int konfirmasi = JOptionPane.showConfirmDialog(
            this, 
            "Yakin ingin menghapus notifikasi ini?", 
            "Konfirmasi Hapus", 
            YES_NO_OPTION
        );
        
        if(konfirmasi == YES_OPTION) {
            MainApp.notifikasiManager.hapusNotifikasi(notif.getIdNotifikasi());
        }
    }//GEN-LAST:event_btnHapusNotifikasiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusNotifikasi;
    private javax.swing.JButton btnTambahObatOTC;
    private javax.swing.JButton btnTambahObatOTC1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JScrollPane contentScrollPane;
    private javax.swing.JPanel headerContainer;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotalNotifikasiBerhasil;
    private javax.swing.JLabel labelTotalNotifikasiInfo;
    private javax.swing.JLabel labelTotalNotifikasiKritis;
    private javax.swing.JLabel labelTotalNotifikasiPeringatan;
    private javax.swing.JLabel lblDescriptionObatOTC;
    private javax.swing.JLabel lblTitleObatOTC;
    private javax.swing.JTable tableNotifikasi;
    private javax.swing.JLabel totalNotifikasiBerhasil;
    private javax.swing.JLabel totalNotifikasiInfo;
    private javax.swing.JLabel totalNotifikasiKritis;
    private javax.swing.JPanel totalNotifikasiKritisPanel;
    private javax.swing.JPanel totalNotifikasiKritisPanel1;
    private javax.swing.JPanel totalNotifikasiKritisPanel2;
    private javax.swing.JPanel totalNotifikasiKritisPanel3;
    private javax.swing.JLabel totalNotifikasiPeringatan;
    // End of variables declaration//GEN-END:variables
}
