package com.mycompany.apotekertest.ui;

import com.mycompany.apotekertest.exception.DuplicateItemException;
import com.mycompany.apotekertest.exception.InvalidInputException;
import java.util.Date;
import com.mycompany.apotekertest.model.*;
import com.mycompany.apotekertest.stok.*;
import java.time.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.*;

public class TambahItem extends javax.swing.JPanel {
    
    
    public TambahItem() {
        initComponents();
        kategoriObatInput.setVisible(false);
        lblKategoriObat.setVisible(false);
        hargaBeliInput.setVisible(false);
        lblHargaBeli.setVisible(false);
        hargaJualInput.setVisible(false);
        lblHargaJual.setVisible(false);
        satuanInput.setVisible(false);
        kategoriInput.setVisible(false);
        lblKategori.setVisible(false);
        //Agar posisi field tidak bergeser saat component dihide 
        ((javax.swing.GroupLayout) this.getLayout()).setHonorsVisibility(false);        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ItemID2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        itemIdInput = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        namaItemInput = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        quantityInput = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        stokMinimumInput = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsiInput = new javax.swing.JTextArea();
        satuanInput = new javax.swing.JComboBox<>();
        JenisItem1 = new javax.swing.JComboBox<>();
        lblKategoriObat = new javax.swing.JLabel();
        kategoriObatInput = new javax.swing.JTextField();
        lblHargaJual = new javax.swing.JLabel();
        lblHargaBeli = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();
        kategoriInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        simpanButton = new javax.swing.JButton();
        hargaJualInput = new javax.swing.JTextField();
        hargaBeliInput = new javax.swing.JTextField();
        expiredDateInput = new javax.swing.JTextField();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Nama Item");

        ItemID2.addActionListener(this::ItemID2ActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ItemID2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ItemID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 145, 55));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Input Data Obat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Item ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        itemIdInput.addActionListener(this::itemIdInputActionPerformed);
        jPanel3.add(itemIdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 38, 198, -1));
        itemIdInput.getAccessibleContext().setAccessibleName("ItemID");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nama Item");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        namaItemInput.addActionListener(this::namaItemInputActionPerformed);
        jPanel4.add(namaItemInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 38, 238, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Kuantitas");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Kuantitas");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel6.add(quantityInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Stok Minimum");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));
        jPanel7.add(stokMinimumInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Deskripsi");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        deskripsiInput.setColumns(20);
        deskripsiInput.setRows(5);
        jScrollPane1.setViewportView(deskripsiInput);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 26, 466, 162));

        satuanInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Satuan", "Kg", "Gram", "mg", "L", "mL" }));
        satuanInput.addActionListener(this::satuanInputActionPerformed);

        JenisItem1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Item", "Obat OTC", "Bahan Racikan", "Non Obat" }));
        JenisItem1.addActionListener(this::JenisItem1ActionPerformed);

        lblKategoriObat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKategoriObat.setText("KategoriObat");

        kategoriObatInput.addActionListener(this::kategoriObatInputActionPerformed);

        lblHargaJual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHargaJual.setText("Harga Jual");

        lblHargaBeli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHargaBeli.setText("Harga Beli");

        lblKategori.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKategori.setText("Kategori");

        kategoriInput.addActionListener(this::kategoriInputActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Kadaluarsa (YYYY-MM-DD)");

        simpanButton.setBackground(new java.awt.Color(0, 145, 55));
        simpanButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        simpanButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanButton.setText("TAMBAH");
        simpanButton.addActionListener(this::simpanButtonActionPerformed);

        expiredDateInput.addActionListener(this::expiredDateInputActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JenisItem1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKategoriObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kategoriObatInput)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblHargaJual)
                                            .addComponent(hargaJualInput, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblHargaBeli)
                                            .addComponent(hargaBeliInput, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKategori)
                                    .addComponent(satuanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kategoriInput, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(expiredDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JenisItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKategoriObat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kategoriObatInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHargaJual)
                            .addComponent(lblHargaBeli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargaJualInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaBeliInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expiredDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(satuanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKategori)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kategoriInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void namaItemInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaItemInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaItemInputActionPerformed

    private void ItemID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemID2ActionPerformed

    private void satuanInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuanInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satuanInputActionPerformed

    private void JenisItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisItem1ActionPerformed
        String jenis = JenisItem1.getSelectedItem().toString().trim();

        // Sembunyikan semua field khusus dulu
        kategoriObatInput.setVisible(false);
        lblKategoriObat.setVisible(false);
        hargaBeliInput.setVisible(false);
        lblHargaBeli.setVisible(false);
        hargaJualInput.setVisible(false);
        lblHargaJual.setVisible(false);
        satuanInput.setVisible(false);
        satuanInput.setVisible(false);
        lblKategori.setVisible(false);
        kategoriInput.setVisible(false);

        // Tampilkan sesuai pilihan
        switch (jenis) {
            case "Obat OTC":
                kategoriObatInput.setVisible(true);
                lblKategoriObat.setVisible(true);
                hargaBeliInput.setVisible(true);
                lblHargaBeli.setVisible(true);
                hargaJualInput.setVisible(true);
                lblHargaJual.setVisible(true);
                break;
            case "Bahan Racikan":
                satuanInput.setVisible(true);
                satuanInput.setVisible(true);
                break;
            case "Non Obat":
                kategoriInput.setVisible(true);
                lblKategori.setVisible(true);
                hargaBeliInput.setVisible(true);
                lblHargaBeli.setVisible(true);
                hargaJualInput.setVisible(true);
                lblHargaJual.setVisible(true);
                break;
        }
    }//GEN-LAST:event_JenisItem1ActionPerformed

    private void kategoriInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriInputActionPerformed

    private void kategoriObatInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriObatInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriObatInputActionPerformed

    private void itemIdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIdInputActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        
        String jenis = JenisItem1.getSelectedItem().toString().trim();
        
        String idItem, namaItem, deskripsi, expiredDate;
        int quantity, stokMinimum;
        double hargaBeli, hargaJual;
   
        
        switch(jenis) {
            case "Obat OTC":
                idItem = itemIdInput.getText();
                namaItem = namaItemInput.getText();
                quantity = Integer.parseInt(quantityInput.getText());
                stokMinimum = Integer.parseInt(stokMinimumInput.getText());
                expiredDate = expiredDateInput.getText();
                deskripsi = deskripsiInput.getText();
                String kategoriObat = kategoriObatInput.getText();
                hargaBeli = Double.parseDouble(hargaBeliInput.getText());
                hargaJual = Double.parseDouble(hargaJualInput.getText());
                
                try{
                    MainApp.stokService.tambahObat(kategoriObat, hargaBeli, hargaJual, idItem, namaItem, quantity, stokMinimum, expiredDate, deskripsi);
                } catch(DuplicateItemException e) {
                    
                } catch (InvalidInputException ex) {
                    System.getLogger(TambahItem.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                break;

            case "Bahan Racikan":
                idItem = itemIdInput.getText();
                namaItem = namaItemInput.getText();
                quantity = Integer.parseInt(quantityInput.getText());
                stokMinimum = Integer.parseInt(stokMinimumInput.getText());
                expiredDate = expiredDateInput.getText();
                deskripsi = deskripsiInput.getText();
                String satuan = satuanInput.getSelectedItem().toString().trim();
                try{
                    MainApp.stokService.tambahBahanRacikan(satuan, idItem, namaItem, quantity, stokMinimum, expiredDate, deskripsi);
                } catch(DuplicateItemException e) {
                    
                } catch (InvalidInputException ex) {
                    System.getLogger(TambahItem.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                
                break;
                
            case "Non Obat":
                idItem = itemIdInput.getText();
                namaItem = namaItemInput.getText();
                quantity = Integer.parseInt(quantityInput.getText());
                stokMinimum = Integer.parseInt(stokMinimumInput.getText());
                expiredDate = expiredDateInput.getText();
                deskripsi = deskripsiInput.getText();
                String kategori = kategoriInput.getText();
                hargaBeli = Double.parseDouble(hargaBeliInput.getText());
                hargaJual = Double.parseDouble(hargaJualInput.getText());
                try{
                    MainApp.stokService.tambahNonObat(kategori, hargaBeli, hargaJual, idItem, namaItem, quantity, stokMinimum, expiredDate, deskripsi);
                } catch(DuplicateItemException e) {
                    
                } catch (InvalidInputException ex) {
                    System.getLogger(TambahItem.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                
                break;
        }
        
        JenisItem1.setSelectedIndex(0);
        itemIdInput.setText("");
        namaItemInput.setText("");
        quantityInput.setText("");
        hargaBeliInput.setText("");
        hargaJualInput.setText("");
        deskripsiInput.setText("");
        expiredDateInput.setText("");
        kategoriObatInput.setText("");
        kategoriInput.setText("");
        satuanInput.setSelectedIndex(0);
        stokMinimumInput.setText("");
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void expiredDateInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiredDateInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiredDateInputActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ItemID2;
    private javax.swing.JComboBox<String> JenisItem1;
    private javax.swing.JTextArea deskripsiInput;
    private javax.swing.JTextField expiredDateInput;
    private javax.swing.JTextField hargaBeliInput;
    private javax.swing.JTextField hargaJualInput;
    private javax.swing.JTextField itemIdInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kategoriInput;
    private javax.swing.JTextField kategoriObatInput;
    private javax.swing.JLabel lblHargaBeli;
    private javax.swing.JLabel lblHargaJual;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblKategoriObat;
    private javax.swing.JTextField namaItemInput;
    private javax.swing.JTextField quantityInput;
    private javax.swing.JComboBox<String> satuanInput;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextField stokMinimumInput;
    // End of variables declaration//GEN-END:variables
}
