package com.apotek.ui;

import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.apotek.model.Item;
import javax.swing.DefaultComboBoxModel;
import java.util.ArrayList;
import javax.swing.JTextField;
/**
 *
 * @author Dean Akmal
 */
public class AuditInput extends javax.swing.JPanel {

    private JTable targetTable;
    private ArrayList<Item> daftarItem = new ArrayList<>();
    
    public AuditInput() {
        initComponents();
        jTextField3.setEditable(false);   // ID Barang: auto-fill, readonly
        jTextField1.setEditable(false);   // Auditor: auto-fill dari user login, readonly
        isiAuditorDariLogin();
        loadNamaItem();
        NamaItem.setEditable(true); // Buka kunci ketikan
        searchFilter(); // Pasang logika filter
    }

    public AuditInput(JTable targetTable) {
        initComponents();
        this.targetTable = targetTable;
        jTextField3.setEditable(false);   // ID Barang: auto-fill, readonly
        jTextField1.setEditable(false);   // Auditor: auto-fill dari user login, readonly
        isiAuditorDariLogin();
        loadNamaItem();
        NamaItem.setEditable(true); // Buka kunci ketikan
        searchFilter(); // Pasang logika filter
    }
    
    // Fitur search dan filter item
    public void searchFilter() {
        JTextField editor = (JTextField) NamaItem.getEditor().getEditorComponent();
        
        // Membaca input klik dari mouse 
        editor.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            // Apabila mouse memencet combo box, text langsug kosong agar pengguna dapat langsung mengetik
            public void mousePressed(java.awt.event.MouseEvent e) {
                if (editor.getText().equals("Pilih Item...")) {
                    editor.setText("");
                }
            }
        });
        
        editor.addKeyListener(new java.awt.event.KeyAdapter() { // Membaca input keyboard
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) { 
                javax.swing.SwingUtilities.invokeLater(() -> { // Multithreading Swing (memastikan aplikasi tidak macet / freeze saat mengetik)
                    //Mengambil input pengguna dari JTextField editor
                    String input = editor.getText(); 
                    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(); // Membuat component ComboBoxModel yang menyimpan list barang / selection
                    model.addElement("Pilih Item...");

                    // Filter pencarian item berdasarkan input
                    for (Item item : daftarItem) {
                        if (item.getNamaItem().toLowerCase().contains(input.toLowerCase())) {
                            model.addElement(item.getNamaItem()); //Menambahkan item yang sesuai input ke selection / pilihan
                        }
                    }
                    
                    //Mengset model JComboBox NamaItem sesuai model baru yang dihasilkan setelah filter
                    NamaItem.setModel(model);
                    editor.setText(input); // Kembalikan teks yang sedang diketik
                    if (!input.isEmpty()) NamaItem.showPopup(); // Tampilkan dropdown otomatis
                });
            }
        });
    }

    private void isiAuditorDariLogin() {
        com.apotek.model.User currentUser = 
            com.apotek.service.LoginSession.getCurrentUser();
        if (currentUser != null) {
            jTextField1.setText(currentUser.getName());
        } else {
            jTextField1.setText("Unknown");
        }
    }   

    public void loadNamaItem(){
    
        daftarItem.clear();
        daftarItem.addAll(MainApp.stokService.getSemuaObat());
        daftarItem.addAll(MainApp.stokService.getSemuaBahanRacikan());
        daftarItem.addAll(MainApp.stokService.getSemuaNonObat());
        
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Pilih Item...");
        
        for (Item item : daftarItem){
            model.addElement(item.getNamaItem());
        }
        
        NamaItem.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ItemID2 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        InputTanggal = new org.jdatepicker.JDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buttonBatal = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        NamaItem = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Nama Item");

        ItemID2.addActionListener(this::ItemID2ActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ItemID2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ItemID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setPreferredSize(new java.awt.Dimension(1034, 587));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 145, 55));
        jLabel9.setText("Audit Input ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 145, 55));
        jLabel1.setText("Tanggal");

        InputTanggal.addActionListener(this::InputTanggalActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 145, 55));
        jLabel2.setText("Nama Barang");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 145, 55));
        jLabel3.setText("Stok Fisik");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setText("cth. OTC-001");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 145, 55));
        jLabel5.setText("ID Barang");

        buttonBatal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(this::buttonBatalActionPerformed);

        buttonSimpan.setBackground(new java.awt.Color(0, 145, 55));
        buttonSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(this::buttonSimpanActionPerformed);

        NamaItem.setEditable(true);
        NamaItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NamaItem.addActionListener(this::NamaItemActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 145, 55));
        jLabel8.setText("Auditor");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(InputTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(NamaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(53, 53, 53))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ItemID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemID2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
            javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        String tanggal;
        if (InputTanggal.getModel().getValue() != null) {
            java.util.Calendar cal = (java.util.Calendar) InputTanggal.getModel().getValue();
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            tanggal = sdf.format(cal.getTime());
        } else {
            JOptionPane.showMessageDialog(this, "Mohon isi tanggal yang valid!");
            return;
        }

        String idBarang = jTextField3.getText().trim();
        String namaBarang = (String) NamaItem.getSelectedItem();
        String stokFisikStr = jTextField2.getText().trim();
        String auditor = jTextField1.getText().trim();

        if (namaBarang == null || namaBarang.equals("Pilih Item...") || idBarang.isEmpty() || stokFisikStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi data wajib!");
            return;
        }

        int stokFisik;
        try {
            stokFisik = Integer.parseInt(stokFisikStr);
            if (stokFisik < 0) {
                JOptionPane.showMessageDialog(this, "Stok Fisik tidak boleh negatif!");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Stok Fisik harus berupa angka bulat!");
            return;
        }

        Item itemDipilih = null;
        for (Item item : daftarItem) {
            if (item.getNamaItem().equals(namaBarang)) {
                itemDipilih = item;
                break;
            }
        }

        if (itemDipilih == null) {
            JOptionPane.showMessageDialog(this, "Item tidak ditemukan di sistem!");
            return;
        }

        int stokSistem = itemDipilih.getQuantity();
        int selisih = stokFisik - stokSistem;
        String statusAudit = (selisih == 0) ? "Sesuai" : "Selisih";

        // Simpan hasil audit ke memory (AuditService), supaya AuditStokPanel bisa nampilinnya
        MainApp.auditService.prosesAudit(itemDipilih, stokFisik, tanggal);

        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void NamaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaItemActionPerformed
        String selected = (String) NamaItem.getSelectedItem();

        if (selected == null || selected.equals("Pilih Item...")) {
            jTextField3.setText("");
            return;
        }

        for (Item item : daftarItem) {
            if (item.getNamaItem().equals(selected)) {
                jTextField3.setText(item.getIdItem());
                break;
            }
        }
    }//GEN-LAST:event_NamaItemActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void InputTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTanggalActionPerformed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdatepicker.JDatePicker InputTanggal;
    private javax.swing.JTextField ItemID2;
    private javax.swing.JComboBox<String> NamaItem;
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
