/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.apotek.ui;

import com.apotek.model.Item;
import com.apotek.service.AuditService;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author himorii
 */
public class AuditStokPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProdukPanel
     */
    public AuditStokPanel() {
        initComponents();
        headerContainer.setLayout(new BorderLayout());
        headerContainer.add(new HeaderPanel(MainApp.stokService), BorderLayout.CENTER);
        contentScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        loadTabelAudit();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        contentScrollPane = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        headerContainer = new javax.swing.JPanel();
        totalItemPendingPanel = new javax.swing.JPanel();
        labelTotalItemPending = new javax.swing.JLabel();
        totalItemPending = new javax.swing.JLabel();
        totalItemSelisihPanel = new javax.swing.JPanel();
        labelTotalItemSelisih = new javax.swing.JLabel();
        totalItemSelisih = new javax.swing.JLabel();
        totalItemSesuaiPanel = new javax.swing.JPanel();
        labelTotalItemSesuai = new javax.swing.JLabel();
        totalItemSesuai = new javax.swing.JLabel();
        totalItemAuditPanel = new javax.swing.JPanel();
        labelTotalItemAudit = new javax.swing.JLabel();
        totalItemAudit = new javax.swing.JLabel();
        lblTitleObatOTC = new javax.swing.JLabel();
        lblDescriptionObatOTC = new javax.swing.JLabel();
        btnBuatAudit = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAuditStok = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnNext1 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setMaximumSize(new java.awt.Dimension(32767, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        contentScrollPane.setMaximumSize(new java.awt.Dimension(32767, 800));
        contentScrollPane.setPreferredSize(new java.awt.Dimension(1082, 800));

        contentPanel.setBackground(new java.awt.Color(240, 252, 245));
        contentPanel.setMaximumSize(new java.awt.Dimension(32767, 800));
        contentPanel.setPreferredSize(new java.awt.Dimension(1080, 800));

        headerContainer.setMinimumSize(new java.awt.Dimension(100, 80));
        headerContainer.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout headerContainerLayout = new javax.swing.GroupLayout(headerContainer);
        headerContainer.setLayout(headerContainerLayout);
        headerContainerLayout.setHorizontalGroup(
            headerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headerContainerLayout.setVerticalGroup(
            headerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        totalItemPendingPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalItemPendingPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalItemPendingPanel.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalItemPending.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalItemPending.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalItemPending.setText("Pending");

        totalItemPending.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalItemPending.setForeground(new java.awt.Color(42, 137, 79));
        totalItemPending.setText("0");

        javax.swing.GroupLayout totalItemPendingPanelLayout = new javax.swing.GroupLayout(totalItemPendingPanel);
        totalItemPendingPanel.setLayout(totalItemPendingPanelLayout);
        totalItemPendingPanelLayout.setHorizontalGroup(
            totalItemPendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalItemPendingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalItemPendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalItemPending, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(totalItemPending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalItemPendingPanelLayout.setVerticalGroup(
            totalItemPendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalItemPendingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalItemPending)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalItemPending, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        totalItemSelisihPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalItemSelisihPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalItemSelisihPanel.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalItemSelisih.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalItemSelisih.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalItemSelisih.setText("Total Obat OTC");

        totalItemSelisih.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalItemSelisih.setForeground(new java.awt.Color(241, 140, 163));
        totalItemSelisih.setText("0");

        javax.swing.GroupLayout totalItemSelisihPanelLayout = new javax.swing.GroupLayout(totalItemSelisihPanel);
        totalItemSelisihPanel.setLayout(totalItemSelisihPanelLayout);
        totalItemSelisihPanelLayout.setHorizontalGroup(
            totalItemSelisihPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalItemSelisihPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalItemSelisihPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalItemSelisih, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(totalItemSelisih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalItemSelisihPanelLayout.setVerticalGroup(
            totalItemSelisihPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalItemSelisihPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalItemSelisih)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalItemSelisih)
                .addContainerGap())
        );

        totalItemSesuaiPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalItemSesuaiPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalItemSesuaiPanel.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalItemSesuai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalItemSesuai.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalItemSesuai.setText("Sesuai");

        totalItemSesuai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalItemSesuai.setForeground(new java.awt.Color(42, 137, 79));
        totalItemSesuai.setText("0");

        javax.swing.GroupLayout totalItemSesuaiPanelLayout = new javax.swing.GroupLayout(totalItemSesuaiPanel);
        totalItemSesuaiPanel.setLayout(totalItemSesuaiPanelLayout);
        totalItemSesuaiPanelLayout.setHorizontalGroup(
            totalItemSesuaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalItemSesuaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalItemSesuaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalItemSesuai, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(totalItemSesuai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalItemSesuaiPanelLayout.setVerticalGroup(
            totalItemSesuaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalItemSesuaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalItemSesuai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalItemSesuai, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        totalItemAuditPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalItemAuditPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(208, 232, 216)));
        totalItemAuditPanel.setForeground(new java.awt.Color(42, 137, 79));

        labelTotalItemAudit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalItemAudit.setForeground(new java.awt.Color(42, 137, 79));
        labelTotalItemAudit.setText("Total Obat OTC");

        totalItemAudit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalItemAudit.setForeground(new java.awt.Color(42, 137, 79));
        totalItemAudit.setText("0");

        javax.swing.GroupLayout totalItemAuditPanelLayout = new javax.swing.GroupLayout(totalItemAuditPanel);
        totalItemAuditPanel.setLayout(totalItemAuditPanelLayout);
        totalItemAuditPanelLayout.setHorizontalGroup(
            totalItemAuditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalItemAuditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalItemAuditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalItemAudit, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(totalItemAudit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalItemAuditPanelLayout.setVerticalGroup(
            totalItemAuditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalItemAuditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalItemAudit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalItemAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblTitleObatOTC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitleObatOTC.setForeground(new java.awt.Color(20, 145, 66));
        lblTitleObatOTC.setText("Catat Audit Stok");

        lblDescriptionObatOTC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescriptionObatOTC.setForeground(new java.awt.Color(42, 137, 79));
        lblDescriptionObatOTC.setText("Pencatatan pengeluaran stok dari gudang");

        btnBuatAudit.setBackground(new java.awt.Color(20, 145, 66));
        btnBuatAudit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuatAudit.setForeground(new java.awt.Color(255, 255, 255));
        btnBuatAudit.setText("Buat Audit Baru");
        btnBuatAudit.addActionListener(this::btnBuatAuditActionPerformed);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(42, 137, 79));
        txtSearch.setText("Cari transaksi, produk...");
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });

        tabelAuditStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang", "Stok Sistem", "Stok Fisik ", "Selisih", "Status", "Auditor", "Tanggal Audit", "Aksi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelAuditStok);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 137, 79));
        jLabel1.setText("Menampilkan 0 dari 0 transaksi");

        btnPrevious.setBackground(new java.awt.Color(20, 145, 66));
        btnPrevious.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious.setText("Sebelumnya");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 137, 79));
        jLabel2.setText("Halaman 0 dari 0");

        btnNext1.setBackground(new java.awt.Color(20, 145, 66));
        btnNext1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNext1.setForeground(new java.awt.Color(255, 255, 255));
        btnNext1.setText("Selanjutnya");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPrevious)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(btnNext1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDescriptionObatOTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTitleObatOTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuatAudit)))
                        .addGap(41, 41, 41))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(totalItemAuditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalItemSesuaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalItemSelisihPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalItemPendingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addComponent(headerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(lblTitleObatOTC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescriptionObatOTC))
                    .addComponent(btnBuatAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalItemAuditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalItemSesuaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalItemSelisihPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalItemPendingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(btnNext1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(3, 3, 3)))
                .addGap(812, 812, 812))
        );

        contentScrollPane.setViewportView(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void loadTabelAudit() {          
        ArrayList<Item> semuaBarang = new ArrayList<>();
        semuaBarang.addAll(MainApp.stokService.getSemuaObat());
        semuaBarang.addAll(MainApp.stokService.getSemuaBahanRacikan());
        semuaBarang.addAll(MainApp.stokService.getSemuaNonObat());

        String[] kolom = {"ID Barang", "Nama Barang", "Stok Sistem", "Stok Fisik", "Selisih", "Status", "Auditor", "Tanggal Audit", "Aksi"};
        Object[][] data = new Object[semuaBarang.size()][kolom.length];

        int totalSesuai = 0, totalSelisih = 0, totalPending = 0;

        for (int i = 0; i < semuaBarang.size(); i++) {
            Item item = semuaBarang.get(i);
            AuditService.HasilAudit hasil = AuditService.getHasilAudit(item.getIdItem());

            data[i][0] = item.getIdItem();
            data[i][1] = item.getNamaItem();
            data[i][2] = item.getQuantity();

            if (hasil == null) {
                data[i][3] = "Belum dicatat";
                data[i][4] = "—";
                data[i][5] = "Pending";
                data[i][6] = "—";
                data[i][7] = "—";
                data[i][8] = "Catat Fisik";
                totalPending++;
            } else {
                data[i][3] = hasil.stokFisik;
                data[i][4] = hasil.selisih;
                data[i][5] = hasil.status;
                data[i][6] = hasil.auditor;
                data[i][7] = hasil.tanggal;
                if (hasil.selisih == 0) {
                    data[i][8] = "—";
                    totalSesuai++;
                } else {
                    data[i][8] = "Ajukan Koreksi";
                    totalSelisih++;
                }
            }
        }

        DefaultTableModel model = new DefaultTableModel(data, kolom) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabelAuditStok.setModel(model);

        totalItemAudit.setText(String.valueOf(semuaBarang.size()));
        totalItemSesuai.setText(String.valueOf(totalSesuai));
        totalItemSelisih.setText(String.valueOf(totalSelisih));
        totalItemPending.setText(String.valueOf(totalPending));

        jLabel1.setText("Menampilkan " + semuaBarang.size() + " dari " + semuaBarang.size() + " transaksi");
    }
  
    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        if(txtSearch.getText().equalsIgnoreCase("Cari transaksi, produk...")) {
            txtSearch.setText("");
        }
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        if(txtSearch.getText().trim().isEmpty()) {
            txtSearch.setText("Cari transaksi, produk...");
        }
    }//GEN-LAST:event_txtSearchFocusLost

    private void btnBuatAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatAuditActionPerformed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(
        (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this),
        "Buat Audit Baru",
        true // modal
        );
        dialog.getContentPane().add(new AuditInput(tabelAuditStok));
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        loadTabelAudit(); 
    }//GEN-LAST:event_btnBuatAuditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuatAudit;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JScrollPane contentScrollPane;
    private javax.swing.JPanel headerContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotalItemAudit;
    private javax.swing.JLabel labelTotalItemPending;
    private javax.swing.JLabel labelTotalItemSelisih;
    private javax.swing.JLabel labelTotalItemSesuai;
    private javax.swing.JLabel lblDescriptionObatOTC;
    private javax.swing.JLabel lblTitleObatOTC;
    private javax.swing.JTable tabelAuditStok;
    private javax.swing.JLabel totalItemAudit;
    private javax.swing.JPanel totalItemAuditPanel;
    private javax.swing.JLabel totalItemPending;
    private javax.swing.JPanel totalItemPendingPanel;
    private javax.swing.JLabel totalItemSelisih;
    private javax.swing.JPanel totalItemSelisihPanel;
    private javax.swing.JLabel totalItemSesuai;
    private javax.swing.JPanel totalItemSesuaiPanel;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
