/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.apotek.ui;

import java.awt.CardLayout;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author himorii
 */
public class DashboardPJApotekerFrame extends JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardPJApotekerFrame.class.getName());

    private CardLayout cardLayout;
    private JPanel contentContainer;
    private DashboardContentPanel dashboardPanel;
    private AuditStokPanel auditStokPanel;
    private ProdukContentPanel produkPanel;
    private LaporanPanel laporanPanel;   

    /**
     * Creates new form DashboardApotekerFrame
     */
    public DashboardPJApotekerFrame() {
        initComponents();

        setTitle("Dashboard PJApoteker");

        initCustomLayout();
        setSize(1366, 768);
        setLocationRelativeTo(null);
    }

    public void showPage(String name) {
        cardLayout.show(contentContainer, name);
        if (name.equals("dashboard")) {
            dashboardPanel.refreshTotalKategori();
        } else if (name.equals("produk")) {
            produkPanel.refreshSemuaTabel();
        }else if (name.equals("laporan")) {
            laporanPanel.refreshLaporan();
        }
    }

    private void initCustomLayout() {
        getContentPane().removeAll();
        getContentPane().setLayout(new BorderLayout());

        SiderbarPJApotekerPanel sidebar = new SiderbarPJApotekerPanel(this);
        dashboardPanel = new DashboardContentPanel();

        JScrollPane dashboardScrollPane = new JScrollPane(dashboardPanel);

        cardLayout = new CardLayout();
        contentContainer = new JPanel(cardLayout);

        dashboardScrollPane.getVerticalScrollBar().setUnitIncrement(16);

        produkPanel = new ProdukContentPanel();
        contentContainer.add(produkPanel, "produk");

        laporanPanel = new LaporanPanel();
        contentContainer.add(laporanPanel, "laporan");
       
        contentContainer.add(dashboardScrollPane, "dashboard");
        contentContainer.add(new StokMasukPanel(), "stokMasuk");
        contentContainer.add(new StokKeluarPanel(), "stokKeluar");
        auditStokPanel = new AuditStokPanel();
        contentContainer.add(auditStokPanel, "auditStok");
        

        contentContainer.add(new NotifikasiPanel(), "notifikasi");

        getContentPane().add(sidebar, BorderLayout.WEST);
        getContentPane().add(contentContainer, BorderLayout.CENTER);

        cardLayout.show(contentContainer, "dashboard");

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 966, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardPJApotekerFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
