package com.apotek.ui;

import com.apotek.model.Apoteker;
import com.apotek.model.User;
import com.apotek.observer.NotifikasiObserver;
import com.apotek.service.LoginSession;
import com.apotek.service.StokService;
import com.apotek.service.UserService;
import javax.swing.Timer;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author Kelompok Kipli
 */
public class HeaderPanel extends javax.swing.JPanel implements NotifikasiObserver {
    private StokService stokService;
    private UserService userService;
    private Timer refreshTimer;
    
    private void loadTanggal() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy", new Locale("id", "ID"));
        lblDate.setText(LocalDate.now().format(formatter));
    }
    
    private void loadShift() {
        User currentUser = LoginSession.getCurrentUser();
        
        if(currentUser == null) {
            lblShift.setText("Belum Login");
            return;
        }
        
        if(currentUser instanceof Apoteker apoteker) {
            lblShift.setText("Shift " + apoteker.getShift());
        } else {
            lblShift.setText("-");
        }
    }
    
    
    @Override
    public void updateNotifikasi() {

        int jumlahAktif = MainApp.notifikasiManager.getJumlahBelumDibaca();
        int stokMenipis = stokService.getJumlahStokMenipis();

        lblNotification.setText(jumlahAktif + " Notifikasi");
        lblStock.setText(stokMenipis + " Stok Menipis");
    }
        

    /**
     * Creates new form HeaderPanel
     */
    public HeaderPanel(StokService stokService) {
        initComponents();
        
        this.stokService = stokService;
        
        MainApp.notifikasiManager.addObserver(this);
        
        loadTanggal();
        loadShift();
        updateNotifikasi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblNotification = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblShift = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(42, 137, 79)));
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(0, 70));
        setPreferredSize(new java.awt.Dimension(0, 70));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(20, 145, 66));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("DASHBOARD INVENTARIS APOTEK");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNotification.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNotification.setForeground(new java.awt.Color(42, 137, 79));
        lblNotification.setText("0 Notifikasi");

        lblStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStock.setForeground(new java.awt.Color(42, 137, 79));
        lblStock.setText("0 Stok Menipis");

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(42, 137, 79));
        lblDate.setText("Kamis, 11 Juni 2025");

        lblShift.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblShift.setForeground(new java.awt.Color(42, 137, 79));
        lblShift.setText("Shift Malam");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 137, 79));
        jLabel1.setText("|");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(42, 137, 79));
        jLabel4.setText("|");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblShift)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNotification)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStock)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShift)
                    .addComponent(lblStock)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblNotification;
    private javax.swing.JLabel lblShift;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
