/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.apotek.ui;

import com.apotek.service.LoginSession;
import com.apotek.model.User;
import java.awt.Color;
import java.awt.Font;
import java.awt.Window;
import javax.swing.JButton;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import static javax.swing.JOptionPane.showConfirmDialog;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.getWindowAncestor;

/**
 *
 * @author himorii
 */
public class SiderbarPJApotekerPanel extends javax.swing.JPanel {
    
    private DashboardPJApotekerFrame parentFrame;
    
    private DashboardContentPanel dashboardPanel;
    private ProdukContentPanel produkPanel;
    
    private void loadUserInfo() {
        User user = LoginSession.getCurrentUser();
        if (user == null) {

            username.setText("Guest");

            role.setText("-");

            return;
        }

        username.setText(user.getName());

        if (user.getClass().getSimpleName().equalsIgnoreCase("PJApoteker")) {
            role.setText("PJ Apoteker");
        } else {
            role.setText("Apoteker");
        }
    }
    
    private void setActiveMenu(JButton activeButton) {
        JButton[] buttons = {
            btnDashboardPanel,
            btnProdukPanel,
            btnStokMasukPanel,
            btnStokKeluarPanel,
            btnAuditStokPanel,
            btnLaporanPanel,
            btnNotifikasiPanel,
            btnLogout
        };
        
        for(JButton btn : buttons){
            btn.setBackground(Color.WHITE);
            btn.setForeground(new Color(0,155,54));
        }
        
        activeButton.setBackground(new Color(199,250,220));

        activeButton.setForeground(new Color(0,100,30));
    }
    
    private void setupSidebar() {
        Color sidebarGreen = new Color(0, 155, 54);

        Color buttonWhite = Color.WHITE;

        Color activeGreen = new Color(199, 250, 220);

        setBackground(sidebarGreen);

        JButton[] buttons = {
            btnDashboardPanel,
            btnProdukPanel,
            btnStokMasukPanel,
            btnStokKeluarPanel,
            btnAuditStokPanel,
            btnLaporanPanel,
            btnNotifikasiPanel,
            btnLogout
        };

        for (JButton btn : buttons) {
            btn.setBackground(buttonWhite);
            btn.setForeground(activeGreen);
            btn.setFocusPainted(false);
            btn.setBorderPainted(false);
            btn.setFont(
                    new Font(
                            "Segoe UI",
                            Font.PLAIN,
                            15
                    )
            );
        }

        btnLogout.setBackground(
                new Color(
                        241,
                        140,
                        163
                )
        );

        btnLogout.setForeground(Color.WHITE);
        btnLogout.setFocusPainted(false);
        btnLogout.setBorderPainted(false);
        username.setFont(
                new Font(
                        "Segoe UI",
                        Font.BOLD,
                        16
                )
        );

        role.setFont(
                new Font(
                        "Segoe UI",
                        Font.PLAIN,
                        13
                )
        );

        role.setForeground(
                new Color(
                        199,
                        250,
                        220
                )
        );

        jSeparator1.setForeground(
                new Color(
                        199,
                        250,
                        220
                )
        );

        jSeparator2.setForeground(
                new Color(
                        199,
                        250,
                        220
                )
        );
    }

    /**
     * Creates new form SiderbarPanel
     */
    public SiderbarPJApotekerPanel(DashboardPJApotekerFrame frame) {
        this.parentFrame = frame;
        
        initComponents();
        setupSidebar();
        loadUserInfo();
        setActiveMenu(btnDashboardPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDashboardPanel = new javax.swing.JButton();
        btnProdukPanel = new javax.swing.JButton();
        btnStokMasukPanel = new javax.swing.JButton();
        btnStokKeluarPanel = new javax.swing.JButton();
        btnAuditStokPanel = new javax.swing.JButton();
        btnLaporanPanel = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnNotifikasiPanel = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 155, 54));
        setMinimumSize(new java.awt.Dimension(240, 700));
        setPreferredSize(new java.awt.Dimension(240, 0));

        btnDashboardPanel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnDashboardPanel.setForeground(new java.awt.Color(0, 155, 54));
        btnDashboardPanel.setText("Dashboard");
        btnDashboardPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboardPanel.setPreferredSize(new java.awt.Dimension(210, 50));
        btnDashboardPanel.addActionListener(this::btnDashboardPanelActionPerformed);

        btnProdukPanel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnProdukPanel.setText("Produk");
        btnProdukPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProdukPanel.setPreferredSize(new java.awt.Dimension(210, 50));
        btnProdukPanel.addActionListener(this::btnProdukPanelActionPerformed);

        btnStokMasukPanel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnStokMasukPanel.setText("Stok Masuk");
        btnStokMasukPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStokMasukPanel.setPreferredSize(new java.awt.Dimension(210, 50));
        btnStokMasukPanel.addActionListener(this::btnStokMasukPanelActionPerformed);

        btnStokKeluarPanel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnStokKeluarPanel.setText("Stok Keluar");
        btnStokKeluarPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStokKeluarPanel.setPreferredSize(new java.awt.Dimension(210, 50));
        btnStokKeluarPanel.addActionListener(this::btnStokKeluarPanelActionPerformed);

        btnAuditStokPanel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnAuditStokPanel.setText("Audit Stok");
        btnAuditStokPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAuditStokPanel.setPreferredSize(new java.awt.Dimension(210, 50));
        btnAuditStokPanel.addActionListener(this::btnAuditStokPanelActionPerformed);

        btnLaporanPanel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnLaporanPanel.setText("Laporan");
        btnLaporanPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporanPanel.setPreferredSize(new java.awt.Dimension(210, 50));
        btnLaporanPanel.addActionListener(this::btnLaporanPanelActionPerformed);

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setHideActionText(true);
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setPreferredSize(new java.awt.Dimension(210, 50));
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APOTEK");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SISTEM INVENTARIS");

        role.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        role.setForeground(new java.awt.Color(199, 250, 220));
        role.setText("PJ APOTEKER");

        username.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("ADMIN");

        btnNotifikasiPanel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnNotifikasiPanel.setText("Notifikasi");
        btnNotifikasiPanel.setHideActionText(true);
        btnNotifikasiPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNotifikasiPanel.setPreferredSize(new java.awt.Dimension(210, 50));
        btnNotifikasiPanel.addActionListener(this::btnNotifikasiPanelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStokMasukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStokKeluarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAuditStokPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLaporanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(role))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNotifikasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(role))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStokMasukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStokKeluarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAuditStokPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLaporanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNotifikasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardPanelActionPerformed
        setActiveMenu(btnDashboardPanel);
        parentFrame.showPage("dashboard");
    }//GEN-LAST:event_btnDashboardPanelActionPerformed

    private void btnProdukPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukPanelActionPerformed
        setActiveMenu(btnProdukPanel);
        parentFrame.showPage("produk");
    }//GEN-LAST:event_btnProdukPanelActionPerformed

    private void btnStokMasukPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokMasukPanelActionPerformed
        setActiveMenu(btnStokMasukPanel);
        parentFrame.showPage("stokMasuk");
    }//GEN-LAST:event_btnStokMasukPanelActionPerformed

    private void btnStokKeluarPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokKeluarPanelActionPerformed
        setActiveMenu(btnStokKeluarPanel);
        parentFrame.showPage("stokKeluar");
    }//GEN-LAST:event_btnStokKeluarPanelActionPerformed

    private void btnAuditStokPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuditStokPanelActionPerformed
        setActiveMenu(btnAuditStokPanel);
        parentFrame.showPage("auditStok");
    }//GEN-LAST:event_btnAuditStokPanelActionPerformed

    private void btnLaporanPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanPanelActionPerformed
        setActiveMenu(btnLaporanPanel);
        parentFrame.showPage("laporan");
    }//GEN-LAST:event_btnLaporanPanelActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Window parent = getWindowAncestor(this);
        
        int confirm = showConfirmDialog(parent, "Apakah kamu yakin ingin keluar?", "Konfirmasi Logout", YES_NO_OPTION, QUESTION_MESSAGE);
        
        if(confirm == YES_OPTION) {
            LoginSession.setCurrentUser(null);
            
            SwingUtilities.invokeLater(() -> {
                new LoginFrame().setVisible(true);
            });
            
            Window window = getWindowAncestor(this);
            
            if(window instanceof JFrame frame) {
                frame.dispose();
            }
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnNotifikasiPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotifikasiPanelActionPerformed
        setActiveMenu(btnNotifikasiPanel);
        parentFrame.showPage("notifikasi");
    }//GEN-LAST:event_btnNotifikasiPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuditStokPanel;
    private javax.swing.JButton btnDashboardPanel;
    private javax.swing.JButton btnLaporanPanel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNotifikasiPanel;
    private javax.swing.JButton btnProdukPanel;
    private javax.swing.JButton btnStokKeluarPanel;
    private javax.swing.JButton btnStokMasukPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel role;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
