package com.apotek.ui;

import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.apotek.model.Item;
import javax.swing.DefaultComboBoxModel;
import java.util.ArrayList;
import javax.swing.JTextField;
/**
 *
 * @author Dean Akmal
 */
public class TambahStokMasuk extends javax.swing.JPanel {

    private JTable targetTable;
    private ArrayList<Item> daftarItem = new ArrayList<>();
    /**
     * Creates new form TambahObat
     */
    public TambahStokMasuk() {
        initComponents();
        loadNamaItem();
        NamaItem.setEditable(true); // Buka kunci ketikan
        searchFilter();        // Pasang logika filter
    }
    
    public TambahStokMasuk(JTable targetTable) {
        initComponents();
        this.targetTable = targetTable;
        loadNamaItem();
        NamaItem.setEditable(true); // Buka kunci ketikan
        searchFilter();        // Pasang logika filter
    }
    
    public void searchFilter() {
        JTextField editor = (JTextField) NamaItem.getEditor().getEditorComponent();
        
        // Membaca input klik dari mouse 
        editor.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            // Apabila mouse memencet combo box, text langsug kosong agar pengguna dapat langsung mengetik
            public void mousePressed(java.awt.event.MouseEvent e) {
                if (editor.getText().equals("Pilih Item...")) {
                    editor.setText("");
                }
            }
        });
        
        editor.addKeyListener(new java.awt.event.KeyAdapter() { // Membaca input keyboard
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) { 
                javax.swing.SwingUtilities.invokeLater(() -> { // Multithreading Swing (memastikan aplikasi tidak macet / freeze saat mengetik)
                    //Mengambil input pengguna dari JTextField editor
                    String input = editor.getText(); 
                    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(); // Membuat component ComboBoxModel yang menyimpan list barang / selection
                    model.addElement("Pilih Item...");

                    // Filter pencarian item berdasarkan input
                    for (Item item : daftarItem) {
                        if (item.getNamaItem().toLowerCase().contains(input.toLowerCase())) {
                            model.addElement(item.getNamaItem()); //Menambahkan item yang sesuai input ke selection / pilihan
                        }
                    }
                    
                    //Mengset model JComboBox NamaItem sesuai model baru yang dihasilkan setelah filter
                    NamaItem.setModel(model);
                    editor.setText(input); // Kembalikan teks yang sedang diketik
                    if (!input.isEmpty()) NamaItem.showPopup(); // Tampilkan dropdown otomatis
                });
            }
        });
    }
    
    public void loadNamaItem(){
    
        daftarItem.clear();
        daftarItem.addAll(MainApp.stokService.getSemuaObat());
        daftarItem.addAll(MainApp.stokService.getSemuaBahanRacikan());
        daftarItem.addAll(MainApp.stokService.getSemuaNonObat());
        
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Pilih Item...");
        
        for (Item item : daftarItem){
            model.addElement(item.getNamaItem());
        }
        
        NamaItem.setModel(model);
    }
    
    
    


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ItemID2 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDatePicker1 = new org.jdatepicker.JDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        buttonBatal = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        NamaItem = new javax.swing.JComboBox<>();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Nama Item");

        ItemID2.addActionListener(this::ItemID2ActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ItemID2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ItemID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setPreferredSize(new java.awt.Dimension(1034, 587));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 145, 55));
        jLabel9.setText("Tambah Stok Masuk");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 145, 55));
        jLabel1.setText("Tanggal");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 145, 55));
        jLabel2.setText("Nama Barang");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 145, 55));
        jLabel3.setText("Jumlah Masuk");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setText("cth. OTC-001");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 145, 55));
        jLabel5.setText("ID Barang");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 145, 55));
        jLabel6.setText("Kategori");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 145, 55));
        jLabel7.setText("Pemasok");

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setText("Nama Pemasok");
        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "Obat OTC", "Bahan Racikan", "Non Obat" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        buttonBatal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(this::buttonBatalActionPerformed);

        buttonSimpan.setBackground(new java.awt.Color(0, 145, 55));
        buttonSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(this::buttonSimpanActionPerformed);

        NamaItem.setEditable(true);
        NamaItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NamaItem.addActionListener(this::NamaItemActionPerformed);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2)
                    .addComponent(NamaItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addContainerGap(789, Short.MAX_VALUE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(145, 145, 145)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addGap(41, 41, 41)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(NamaItem))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addContainerGap(529, Short.MAX_VALUE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ItemID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemID2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
            javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed

        if (jDatePicker1.getModel().getValue() == null) {
            JOptionPane.showMessageDialog(this, "Mohon pilih tanggal terlebih dahulu!");
            return;
        }
        
        String tanggal = "";
        if (jDatePicker1.getModel().getValue() != null) {
            java.util.Calendar cal = (java.util.Calendar) jDatePicker1.getModel().getValue();
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            tanggal = sdf.format(cal.getTime());
        }
        String idBarang = jTextField3.getText().trim();
        String namaBarang = (String) NamaItem.getSelectedItem();
        String kategori = (String) jComboBox1.getSelectedItem();
        String jumlahMasukStr = jTextField2.getText().trim();
        String pemasok = jTextField5.getText().trim();

        if (namaBarang.isEmpty() || idBarang.isEmpty() || jumlahMasukStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi data wajib (ID Barang, Nama Barang, Jumlah Masuk)!");
            return;
        }
        
         int jumlahMasuk;
        try {
            jumlahMasuk = Integer.parseInt(jumlahMasukStr);
            if (jumlahMasuk <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah Masuk harus lebih dari 0!");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah Masuk harus berupa angka bulat!");
            return;
        }

        // Cari item yang dipilih di daftarItem
        Item itemDipilih = null;
        for (Item item : daftarItem) {
            if (item.getNamaItem().equals(namaBarang)) {
                itemDipilih = item;
                break;
            }
        }

        if (itemDipilih == null) {
            JOptionPane.showMessageDialog(this, "Item tidak ditemukan di sistem!");
            return;
        }

        // Tambahkan stok riil melalui StokService sesuai jenis item
        try {
            int stokBaru = itemDipilih.getQuantity() + jumlahMasuk; // <-- DITAMBAH, bukan dikurangi
            itemDipilih.setQuantity(stokBaru);

            if (itemDipilih instanceof com.apotek.model.ObatOTC) {
                MainApp.stokService.tambahStok((com.apotek.model.ObatOTC) itemDipilih, jumlahMasuk, pemasok);
            } else if (itemDipilih instanceof com.apotek.model.BahanRacikan) {
                MainApp.stokService.tambahStok((com.apotek.model.BahanRacikan) itemDipilih, jumlahMasuk, pemasok);
            } else if (itemDipilih instanceof com.apotek.model.NonObat) {
                MainApp.stokService.tambahStok((com.apotek.model.NonObat) itemDipilih, jumlahMasuk, pemasok);
            }
        } catch (com.apotek.exception.ItemNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Gagal update stok: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

            if (targetTable != null) {
                DefaultTableModel model = (DefaultTableModel) targetTable.getModel();

        Object[] data = {
            namaBarang,
            idBarang,
            kategori,
            jumlahMasukStr,
            tanggal,
            pemasok
        };

        boolean ditemukanKosong = false;

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0) == null) {
                for (int j = 0; j < data.length; j++) {
                    model.setValueAt(data[j], i, j);
                }
                ditemukanKosong = true;
                break;
            }
        }

        if (!ditemukanKosong) {
            model.addRow(data);
        }
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    
    private void NamaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaItemActionPerformed
        String selected = (String) NamaItem.getSelectedItem();

        if(selected == null || selected.equals("Pilih Item...")){
            jTextField3.setText("");
            jComboBox1.setSelectedIndex(0);
            return;
        }

        for (Item item : daftarItem) {
            if (item.getNamaItem().equals(selected)) {

                jTextField3.setText(item.getIdItem());

                // Tentukan kategori otomatis berdasarkan jenis item
                if (item instanceof com.apotek.model.ObatOTC) {
                    jComboBox1.setSelectedItem("Obat OTC");
                } else if (item instanceof com.apotek.model.BahanRacikan) {
                    jComboBox1.setSelectedItem("Bahan Racikan");
                } else if (item instanceof com.apotek.model.NonObat) {
                    jComboBox1.setSelectedItem("Non Obat");
                }
                break;
            }
        }

    }//GEN-LAST:event_NamaItemActionPerformed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ItemID2;
    private javax.swing.JComboBox<String> NamaItem;
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JComboBox<String> jComboBox1;
    private org.jdatepicker.JDatePicker jDatePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
